version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["java", "-jar", "app.jar"]

volumes:
  mysql_data:
